## Emilio Torres Manzanera
## University of Oviedo
## Time-stamp: <2018-05-23 12:36 emilio on emilio-despacho>
## ============================================================

# ----------------- Helper Functions -----------------

## Draw a single segment (bone) of the stick figure
bone <- function(begin, distance, angle, ratioxy, mapping, data, ...) {
  ## requires: begin=c(x,y), distance, angle, ratioxy
  end <- c(begin[1] + distance * cos(angle) * ratioxy,
           begin[2] + distance * sin(angle))
  
  # Use the modernized geom_xkcdpath instead of xkcdline
  geom_xkcdpath(
    mapping = aes(x = begin[1], y = begin[2], xend = end[1], yend = end[2]),
    data = data.frame(xmin = begin[1], ymin = begin[2], xmax = end[1], ymax = end[2]),
    ...
  )
}

## Draw the head of the stick figure (a circle)
head <- function(centerofhead, diameter, ratioxy, mapping, data, ...) {
  # The original data argument is ignored, and a new data frame
  # containing the calculated diameter and center is used.
  
  # Use the modernized geom_xkcdpath instead of xkcdline
  # geom_xkcdpath naturally handles the diameter aesthetic
  geom_xkcdpath(
    mapping = aes(x = centerofhead[1], y = centerofhead[2], diameter = diameter),
    data = data.frame(
      x = centerofhead[1],
      y = centerofhead[2],
      diameter = diameter
    ),
    ratioxy = ratioxy,
    mask = TRUE,
    ...
  )
  # The old logic for creating 'newmapping' to manually pass diameter is removed
  # as the new GeomXkcdPath handles it directly via the 'diameter' aesthetic.
}

# ----------------- Main Function -----------------

#' @title Draw a stick figure
#'
#' @description This function draws an XKCD style stick figure.
#'
#' The following aesthetics are required:
#' \itemize{
#'   \item x: x position of the center of the head.
#'   \item y: y position of the center of the head.
#'   \item scale: scale of the man (size in Y axis units).
#'   \item ratioxy: Ratio x to y of the graph (Use \code{diff(xrange) / diff(yrange)}).
#'   \item angleofspine: angle between the spine and a horizontal line.
#'   \item anglerighthumerus, anglelefthumerus, etc.: angles for limbs.
#'   \item angleofneck: angle for the neck segment.
#' }
#'
#' @param mapping Mapping between variables and aesthetics generated by \code{\link[ggplot2]{aes}}.
#' @param data Dataset used in this layer.
#' @param ... Other arguments passed to geom_xkcdpath.
#' @return A list of layers forming the stick figure.
#' @seealso   \code{\link[ggplot2]{aes}}, \code{\link{geom_xkcdpath}}
#' @import ggplot2
#' @export
#' @examples
#' \dontrun{
#' man <- data.frame(x=1,y=1,scale=1,ratioxy=1,
#'                   angleofspine= -90,
#'                   anglerighthumerus=-120,anglelefthumerus=-60,
#'                   anglerightradius=-120,angleleftradius=-60,
#'                   anglerightleg=-140,angleleftleg=-140,
#'                   angleofneck=-90)
#' p <- ggplot() + xkcdman(aes(x=x,y=y,scale=scale,ratioxy=ratioxy,
#'                             angleofspine=angleofspine,
#'                             anglerighthumerus=anglerighthumerus,
#'                             anglelefthumerus=anglelefthumerus,
#'                             anglerightradius=anglerightradius,
#'                             angleleftradius=angleleftradius,
#'                             anglerightleg=anglerightleg,
#'                             angleleftleg=angleleftleg,
#'                             angleofneck=angleofneck),
#'                        data=man) + xkcdaxis(c(0,2),c(0,2))
#' p
#' }
xkcdman <- function(mapping, data, ...) {
  # 1. Define man dimensions based on 'scale'
  lengthofhead <- data$scale * 0.2
  lengthofneck <- data$scale * 0.1
  lengthofspine <- data$scale * 0.4
  lengthofhumerus <- data$scale * 0.2
  lengthofradius <- data$scale * 0.2
  lengthofleg <- data$scale * 0.3
  
  diameterofhead <- lengthofhead
  centerofhead <- c(data$x, data$y)
  
  # 2. Calculate coordinates for joints
  beginneck <- c(centerofhead[1] + lengthofhead/2 * cos(data$angleofneck*pi/180) * data$ratioxy,
                 centerofhead[2] + lengthofhead/2 * sin(data$angleofneck*pi/180))
  
  endneck <- c(beginneck[1] + lengthofneck * cos(data$angleofneck*pi/180) * data$ratioxy,
               beginneck[2] + lengthofneck * sin(data$angleofneck*pi/180))
  beginspine <- endneck
  
  endspine <- c(beginspine[1] + lengthofspine * cos(data$angleofspine*pi/180) * data$ratioxy,
                beginspine[2] + lengthofspine * sin(data$angleofspine*pi/180))
  
  endrighthumerus <- c(beginspine[1] + lengthofhumerus * cos(data$anglerighthumerus*pi/180) * data$ratioxy,
                       beginspine[2] + lengthofhumerus * sin(data$anglerighthumerus*pi/180))
  anglerightradius <- data$anglerightradius * pi/180
  
  endlefthumerus <- c(beginspine[1] + lengthofhumerus * cos(data$anglelefthumerus*pi/180) * data$ratioxy,
                      beginspine[2] + lengthofhumerus * sin(data$anglelefthumerus*pi/180))
  angleleftradius <- data$angleleftradius * pi/180
  
  # 3. Assemble the stick figure layers
  
  figurelayers <- list(
    # Head (Circle)
    head(centerofhead = centerofhead, diameter = diameterofhead,
         ratioxy = data$ratioxy, mapping = mapping, data = data, ...),
    
    # Neck (Bone)
    bone(begin = beginneck, distance = lengthofneck,
         angle = data$angleofneck * pi/180, ratioxy = data$ratioxy,
         mapping = mapping, data = data, ...),
    
    # Spine (Bone)
    bone(begin = beginspine, distance = lengthofspine,
         angle = data$angleofspine * pi/180, ratioxy = data$ratioxy,
         mapping = mapping, data = data, ...),
    
    # Right Arm: Humerus (Bone)
    bone(begin = beginspine, distance = lengthofhumerus,
         angle = data$anglerighthumerus * pi/180, ratioxy = data$ratioxy,
         mapping = mapping, data = data, ...),
    
    # Right Arm: Radius (Bone)
    bone(begin = endrighthumerus, distance = lengthofradius,
         angle = data$anglerightradius * pi/180, ratioxy = data$ratioxy,
         mapping = mapping, data = data, ...),
    
    # Left Arm: Humerus (Bone)
    bone(begin = beginspine, distance = lengthofhumerus,
         angle = data$anglelefthumerus * pi/180, ratioxy = data$ratioxy,
         mapping = mapping, data = data, ...),
    
    # Left Arm: Radius (Bone)
    bone(begin = endlefthumerus, distance = lengthofradius,
         angle = data$angleleftradius * pi/180, ratioxy = data$ratioxy,
         mapping = mapping, data = data, ...),
    
    # Right Leg (Bone)
    bone(begin = endspine, distance = lengthofleg,
         angle = data$anglerightleg * pi/180, ratioxy = data$ratioxy,
         mapping = mapping, data = data, ...),
    
    # Left Leg (Bone)
    bone(begin = endspine, distance = lengthofleg,
         angle = data$angleleftleg * pi/180, ratioxy = data$ratioxy,
         mapping = mapping, data = data, ...)
  )
  
  # Flatten the list of layers and return
  do.call(c, figurelayers)
}