## Emilio Torres Manzanera
## University of Oviedo
## Time-stamp: <2018-05-23 17:40 emilio on emilio-despacho>
## ============================================================


##' It draws fuzzy rectangles.
##'
##' This function draws rectangles with hand-drawn, wobbly borders.
##'
##' The following aesthetics are required:
##' \enumerate{
##'   \item xmin
##'   \item ymin
##'   \item xmax
##'   \item ymax
##' }
##' The fill and border are controlled with the standard \code{fill},
##' \code{colour} and \code{linewidth} aesthetics, so they may be mapped to
##' variables in the usual way.
##' @title Draw fuzzy rectangles
##' @param mapping Mapping between variables and aesthetics generated by \code{\link[ggplot2]{aes}}. See Details.
##' @param data Dataset used in this layer.
##' @param stat The statistical transformation to use on the data for this layer.
##' @param position Position adjustment.
##' @param borderxjitteramount Horizontal jitter amount for the border.
##' @param borderyjitteramount Vertical jitter amount for the border.
##' @param wobble Scalar multiplier applied to both jitter amounts. \code{1} leaves
##'   them unchanged; \code{0} draws straight borders.
##' @param seed Optional integer for a reproducible border. See \code{\link{geom_xkcdpath}}.
##' @param na.rm If \code{FALSE}, missing values are removed with a warning.
##' @param show.legend Show legend.
##' @param inherit.aes Whether to inherit aesthetics from the plot.
##' @param fillcolour Deprecated. Use the \code{fill} aesthetic.
##' @param bordercolour Deprecated. Use the \code{colour} aesthetic.
##' @param borderlinewidth Deprecated. Use the \code{linewidth} aesthetic.
##' @param ... Other arguments passed on to \code{\link[ggplot2]{layer}}.
##' @return A layer.
##' @seealso \code{\link[ggplot2]{aes}}, \code{\link{geom_xkcdpath}}
##' @keywords manip
##' @import ggplot2
##' @export
##' @examples
#' \dontrun{
#' volunteers <- data.frame(year = c(2007:2011),
#'                          number = c(56470, 56998, 59686, 61783, 64251))
#'
#' xrange <- range(volunteers$year)
#' yrange <- range(volunteers$number)
#'
#' p <- ggplot() +
#'      xkcdrect(aes(xmin = year - 0.2,
#'                   xmax = year + 0.2,
#'                   ymin = number - 500,
#'                   ymax = number + 500),
#'               data = volunteers,
#'               fill = "pink",
#'               linewidth = 1.2) +
#'      geom_point(aes(x = year, y = number), data = volunteers) +
#'      xkcdaxis(xrange, yrange) +
#'      theme_xkcd()
#' p
#' }
xkcdrect <- function(mapping = NULL, data = NULL, stat = "identity",
                     position = "identity", ...,
                     borderxjitteramount = 0.005, borderyjitteramount = 0.005,
                     wobble = 1, seed = NULL, na.rm = FALSE,
                     show.legend = NA, inherit.aes = TRUE,
                     fillcolour, bordercolour, borderlinewidth) {

  # Deprecated arguments, kept working for one release.
  params <- list(...)
  if (!missing(fillcolour)) {
    warning("'fillcolour' is deprecated; use the 'fill' aesthetic instead.",
            call. = FALSE)
    if (is.null(params$fill)) params$fill <- fillcolour
  }
  if (!missing(bordercolour)) {
    warning("'bordercolour' is deprecated; use the 'colour' aesthetic instead.",
            call. = FALSE)
    if (is.null(params$colour)) params$colour <- bordercolour
  }
  if (!missing(borderlinewidth)) {
    warning("'borderlinewidth' is deprecated; use the 'linewidth' aesthetic instead.",
            call. = FALSE)
    if (is.null(params$linewidth)) params$linewidth <- borderlinewidth
  }

  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomXkcdRect,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = c(list(borderxjitteramount = borderxjitteramount,
                    borderyjitteramount = borderyjitteramount,
                    wobble = wobble,
                    seed = seed,
                    na.rm = na.rm),
               params)
  )
}

#' GeomXkcdRect: fuzzy rectangle geom (XKCD style)
#'
#' Draws each rectangle as a standard filled rect with four jittered,
#' Bezier-smoothed border segments on top.
#'
#' @format NULL
#' @usage NULL
#' @export
GeomXkcdRect <- ggplot2::ggproto(
  "GeomXkcdRect",
  ggplot2::Geom,
  required_aes = c("xmin", "xmax", "ymin", "ymax"),
  default_aes = ggplot2::aes(colour = "black", fill = "grey90", linewidth = 0.5,
                             linetype = 1, alpha = NA),
  # NOTE: no `...` in draw_panel() below. ggplot2's Geom$parameters() falls back
  # to draw_group()'s formals whenever draw_panel() accepts dots, which would
  # leave this geom with no recognised parameters and silently ignore them all.
  extra_params = c("borderxjitteramount", "borderyjitteramount", "wobble",
                   "seed", "na.rm"),
  draw_panel = function(self, data, panel_params, coord,
                        borderxjitteramount = 0.005, borderyjitteramount = 0.005,
                        wobble = 1, seed = NULL, na.rm = FALSE) {
    if (nrow(data) == 0) return(grid::nullGrob())

    borderxjitteramount <- borderxjitteramount * wobble
    borderyjitteramount <- borderyjitteramount * wobble

    # 1. Fill, drawn by the stock rect geom with no outline of its own
    filldata <- data
    filldata$colour <- NA
    fillgrob <- ggplot2::GeomRect$draw_panel(filldata, panel_params, coord)

    # 2. Borders: four edges per rectangle, expanded into wobbly paths.
    #    Horizontal edges wobble vertically and vice versa.
    aesth_cols <- setdiff(names(data),
                          c("xmin", "xmax", "ymin", "ymax", "fill", "PANEL", "group"))
    edges <- list(
      list(x = "xmin", y = "ymax", xend = "xmax", yend = "ymax", horizontal = TRUE),
      list(x = "xmax", y = "ymin", xend = "xmax", yend = "ymax", horizontal = FALSE),
      list(x = "xmin", y = "ymin", xend = "xmin", yend = "ymax", horizontal = FALSE),
      list(x = "xmin", y = "ymin", xend = "xmax", yend = "ymin", horizontal = TRUE)
    )

    paths <- vector("list", nrow(data) * length(edges))
    k <- 0
    for (i in seq_len(nrow(data))) {
      row <- data[i, , drop = FALSE]
      rowseed <- if (is.null(seed)) NULL else seed + i
      for (e in seq_along(edges)) {
        edge <- edges[[e]]
        df <- pointssegment(
          x = row[[edge$x]], y = row[[edge$y]],
          xend = row[[edge$xend]], yend = row[[edge$yend]],
          xjitteramount = if (edge$horizontal) 0 else borderxjitteramount,
          yjitteramount = if (edge$horizontal) borderyjitteramount else 0,
          seed = if (is.null(rowseed)) NULL else rowseed + e
        )
        for (nm in aesth_cols) df[[nm]] <- row[[nm]]
        k <- k + 1
        df$group <- k
        paths[[k]] <- df
      }
    }

    borderdata <- do.call(rbind, paths)
    bordergrob <- ggplot2::GeomPath$draw_panel(borderdata, panel_params, coord)

    grid::grobTree(fillgrob, bordergrob)
  },

  draw_key = ggplot2::draw_key_polygon
)
