## Emilio Torres Manzanera
## University of Oviedo
## Time-stamp: <2018-05-23 17:40 emilio on emilio-despacho>
## ============================================================


#' @title Draw fuzzy rectangles
#'
#' @description This function draws fuzzy rectangles by plotting four separate, jittered line segments.
#'
#' It plots rectangles. The following aesthetics are required:
#' \itemize{
#'   \item xmin
#'   \item ymin
#'   \item xmax
#'   \item ymax
#' }
#' Additionally, you can use the aesthetics of \code{\link[ggplot2]{geom_path}} and \code{\link[ggplot2]{geom_rect}}, as well as parameters for \code{\link{geom_xkcdpath}}.
#'
#' @param mapping Mapping between variables and aesthetics generated by \code{\link[ggplot2]{aes}}. See Details.
#' @param data Dataset used in this layer.
#' @param fillcolour Colour for the fill of the rectangle.
#' @param bordercolour Colour for the border of the rectangle.
#' @param bordersize Size for the border of the rectangle (passed to size aesthetic).
#' @param borderxjitteramount Jitter on the X-axis for vertical borders.
#' @param borderyjitteramount Jitter on the Y-axis for horizontal borders.
#' @param ... Other arguments passed to geom_xkcdpath.
#' @return A list of layers for the rectangle.
#' @seealso   \code{\link[ggplot2]{aes}},  \code{\link[ggplot2]{geom_path}}
#' @import ggplot2
#' @export
#' @examples
#' \dontrun{
#' volunteers <- data.frame(year=c(2007:2011),
#'                         number=c(56470, 56998,59686, 61783, 64251))
#' p <- ggplot() + xkcdrect(aes(xmin = year,
#'                              xmax= year +0.3,
#'                              ymin= number - 500,
#'                              ymax= number + 500),
#'                              data=volunteers, fillcolour = "pink")
#' p
#' }
xkcdrect <- function(mapping, data, ...,
                     fillcolour = "grey90", bordercolour = "black",
                     borderlinewidth = 0.5, borderxjitteramount = 0.005,
                     borderyjitteramount = 0.005) {
  
  # 1. Fill Layer (uses standard geom_rect)
  filllayer <- geom_rect(mapping, data, fill = fillcolour, colour = NA, ...)
  
  # 2. Border Layers (uses modernized geom_xkcdpath for each side)
  
  # Upper Line
  upperline <- geom_xkcdpath(
    mapping = aes(x = xmin, y = ymax, xend = xmax, yend = ymax),
    data = data,
    colour = bordercolour,
    linewidth = bordersize,
    yjitteramount = borderyjitteramount,
    mask = FALSE,
    ...
  )
  
  # Right Line
  rightline <- geom_xkcdpath(
    mapping = aes(x = xmax, y = ymin, xend = xmax, yend = ymax),
    data = data,
    colour = bordercolour,
    linewidth = bordersize,
    xjitteramount = borderxjitteramount,
    mask = FALSE,
    ...
  )
  
  # Left Line
  leftline <- geom_xkcdpath(
    mapping = aes(x = xmin, y = ymin, xend = xmin, yend = ymax),
    data = data,
    colour = bordercolour,
    linewidth = bordersize,
    xjitteramount = borderxjitteramount,
    mask = FALSE,
    ...
  )
  
  # Bottom Line
  bottomline <- geom_xkcdpath(
    mapping = aes(x = xmin, y = ymin, xend = xmax, yend = ymin),
    data = data,
    colour = bordercolour,
    linewidth = bordersize,
    yjitteramount = borderyjitteramount,
    mask = FALSE,
    ...
  )
  
  # Combine all layers
  list(filllayer, upperline, rightline, leftline, bottomline)
}